---
- name: Install Dependencies
  action: apt pkg={{ item }}
    state=present
    update_cache=yes
    cache_valid_time=3600

  with_items:
    - nginx

- name: Copy application sources to www
  copy: src=callback dest=/var/www/html

- name: Copy application config to www
  template: src=config.js.j2 dest=/var/www/html/callback/js/config.js

- name: Copy ssl config
  template: src=ssl.conf.j2 dest=/etc/nginx/sites-enabled/ssl.conf
